export async function generatePDF(mealPlan: any, profile: any) {
  try {
    // Create PDF content
    const pdfContent = `
    PERSONALIZED MEAL PLAN
    
    Profile Information:
    - Height: ${profile.height}cm
    - Weight: ${profile.weight}kg
    - Age: ${profile.age}
    - Gender: ${profile.gender}
    - Activity Level: ${profile.activityLevel}
    - Goal: ${profile.goal}
    - Health Conditions: ${profile.healthConditions.join(", ") || "None"}
    
    7-Day Meal Plan:
    ${
      mealPlan.days
        ?.map(
          (day: any, index: number) => `
    Day ${index + 1}:
    Breakfast: ${day.breakfast}
    Lunch: ${day.lunch}
    Dinner: ${day.dinner}
    Snacks: ${day.snacks || "None"}
    `,
        )
        .join("\n") || ""
    }
    
    Recommendations:
    ${mealPlan.recommendations?.map((rec: string) => `- ${rec}`).join("\n") || ""}
    
    Shopping List:
    ${mealPlan.shoppingList?.map((item: string) => `- ${item}`).join("\n") || ""}
    
    Generated by NutriScan AI
    Date: ${new Date().toLocaleDateString()}
    `

    // Create and download the PDF
    const blob = new Blob([pdfContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `meal-plan-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (error) {
    console.error("Error generating PDF:", error)
    throw error
  }
}
