import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export async function generatePDF(mealPlan: any, profile: any) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4

  const { width, height } = page.getSize();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = height - 50;

  // Title
  page.drawText('PERSONALIZED MEAL PLAN', {
    x: 50,
    y,
    size: 22,
    font: boldFont,
    color: rgb(0, 0.53, 0.71), // nice blue
  });
  y -= 30;

  // Divider
  page.drawLine({
    start: { x: 50, y },
    end: { x: width - 50, y },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  y -= 20;

  // Profile Section
  page.drawText('Profile Information', {
    x: 50,
    y,
    size: 16,
    font: boldFont,
  });
  y -= 20;

  const profileLines = [
    `Height: ${profile.height} cm`,
    `Weight: ${profile.weight} kg`,
    `Age: ${profile.age}`,
    `Gender: ${profile.gender}`,
    `Activity Level: ${profile.activityLevel}`,
    `Goal: ${profile.goal}`,
    `Health Conditions: ${profile.healthConditions?.join(', ') || 'None'}`,
  ];

  profileLines.forEach(line => {
    page.drawText(`- ${line}`, { x: 60, y, size: 12, font });
    y -= 16;
  });

  y -= 10;

  // Meal Plan Section
  page.drawText('7-Day Meal Plan', {
    x: 50,
    y,
    size: 16,
    font: boldFont,
  });
  y -= 20;

  mealPlan.days?.forEach((day: any, index: number) => {
    page.drawText(`Day ${index + 1}`, {
      x: 55,
      y,
      size: 14,
      font: boldFont,
      color: rgb(0, 0, 0),
    });
    y -= 16;

    const dayLines = [
      `Breakfast: ${day.breakfast}`,
      `Lunch: ${day.lunch}`,
      `Dinner: ${day.dinner}`,
      `Snacks: ${day.snacks || 'None'}`,
    ];

    dayLines.forEach(line => {
      page.drawText(`• ${line}`, { x: 70, y, size: 12, font });
      y -= 15;
    });

    y -= 10;
  });

  // Recommendations Section
  if (mealPlan.recommendations?.length) {
    page.drawText('Recommendations', {
      x: 50,
      y,
      size: 16,
      font: boldFont,
    });
    y -= 20;

    mealPlan.recommendations.forEach((rec: string) => {
      page.drawText(`- ${rec}`, { x: 60, y, size: 12, font });
      y -= 15;
    });

    y -= 10;
  }

  // Shopping List Section
  if (mealPlan.shoppingList?.length) {
    page.drawText('Shopping List', {
      x: 50,
      y,
      size: 16,
      font: boldFont,
    });
    y -= 20;

    mealPlan.shoppingList.forEach((item: string) => {
      page.drawText(`• ${item}`, { x: 60, y, size: 12, font });
      y -= 15;
    });

    y -= 10;
  }

  // Footer
  y -= 20;
  page.drawLine({
    start: { x: 50, y },
    end: { x: width - 50, y },
    thickness: 0.5,
    color: rgb(0.8, 0.8, 0.8),
  });
  y -= 15;

  page.drawText('Generated by NutriScan AI', { x: 50, y, size: 10, font });
  y -= 12;
  page.drawText(`Date: ${new Date().toLocaleDateString()}`, { x: 50, y, size: 10, font });

  // Save & download
  const pdfBytes = await pdfDoc.save();
  const blob = new Blob([pdfBytes], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = `meal-plan-${new Date().toISOString().split('T')[0]}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
